---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rier5192/public_html/
    - /usr/bin/rsync -av --exclude='.git' --exclude='.cpanel.yml' --exclude='node_modules' --exclude='vendor' --exclude='dompdf' --exclude='invoices' . $DEPLOYPATH
